language: node_js
node_js:
- stable
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- .ci/lerna.sh
script:
- npm run publish -- --git-remote=ci
env:
  global:
  - secure: "jFW5x6CJFAXHxvWlmpobAWkKkQtBfLSquia3PdyOfw/3CK6x581Ia9nNlvVm6gnqHSB9XFmbIy4cFaVwr/AV92SR9OzyA9EBV7tZsqLQ3ManaLBPxmczaCPIn5GyRj6huT6FDPXfzLsgvCzg/kYP5yhKHe6SEU90j9wqCleN7zWg/74vMZ014sFPAQF6CLissbSHMqtAhX73aPjEapMxg2V5S7/7mB4x4bZnYJmA6u3fdjrRiMIRSD4WkFo9MC3tZWjF9d5g/uZJR2np+k50vk4oYj3a45cacqyudthQOD49f4CqVv7zTuhtlvRxKvThq55BFwOnlSOkyL6o8OjsDv4aQVCJOw1UamrE4qZIQvBuj7VfFagMKffP5+xx3KPuV6Z2gcTPDmNyadkZSdgC+xlTUQFM8IWqrbZ8qZc4YUTKJQb6X5aZGnhrqKNbB8LFUqZGo3WcOi6MbOeabff7LQj7GR1MkgaMVf4QwItCc6utG15dHCOxAqse+F/XUYDDmg2i5ZaTv/LAkLzMmqeEqzK46Kr3gC/gncxIPsjWc1D8qdePdQhnzREgcV3fkYQPAcrG5mJXkgK8QYBI76jPYfmtVHcoUfMxxJo8QTZU3RmWxL4PFTkeTnXlLHRNxYUa+qI8hvdbPHDtP9rmiuFZrgSs5Pe+iG1HEiXAExWzQtg="
  - secure: e1la7AumJL8LUcYzFiY+6fnk/UiCCFbtbSlQPyF/65G7faS96hoAOPqVFoL8d/1LxuwyAmdlijivgYOFxbgTex5ZlvMg2rFap/zzhf0WUGoOfzS8xS9AuC2KiV5OF0dqsOVfr3Lm6wCxXc+cJhk9rO7+BisDIWFiKTpdJtBX5ucywLl2E6ruR8a6vLEYL8CVBSzdNnEDLMZaJ/E24QwFzSRPSkGNABFQMWVnsbawoTQ7Nid0aReX2CkEix0t9VqXRsyLtwyODRNA7HGVkGLedSj1NBI6RWTuO+fWlwhAXhPYOjR/HCJLYkjmQuww3Ek1yDv3E5L0ND+tN1BaKamqDkpFi2IP/cm0WjSOM0lpr4TUiSymXhBegLX6tfrWIxXz4sLKeEOQBqD9pMSyzFfrFMEk9dVGnw6M4v2razKduiAmMV+i06fFd5Pozusv3jf1142jMf80SjX8gYXxGjgHrPqD1fAKpH93kPxH8guYKovqgUgtUMCXUGW1YZNY1ypc/0+RWNNy805ni9XgBOFiAkcTbInTFJBH1E4qcCSkgFfk6Ivonqt7sA5C9CE9tBSb4cTV5txwjSb86I4rNPPf3Ya5FTJBf/L9Bh68nVrSHXXFTmTOj8JQDYEB0HHlCrp2Gc/TouVUXruwUXf7+unwP0TO1wXmGeWPSfqWD96aTzA=
