language: node_js
node_js:
- stable
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- ".ci/lerna.sh"
script:
- npm run publish -- --git-remote=ci
env:
  global:
  - secure: M3jehZcDd02/0kC/w0y4SnJLdMTJGjlwXFM5UEdqrdi33CKikBncVOGJFLZcVfjA0xD+6tJctakMOtRlkm9g4ZMbGvzH8m8Ndo8Hjp/yQOcrxKJV5w78R4TCnFdBdwWGP5LVGtOuKREX15FCRv56IYv9mjHueOua/zTIvmC+wHs5P2Cp3kHlTYqkgVZm3sUX21p35cdyAiz4qx9uTdbJeeY69IjCVA7Py895y8gkHlwdp2et+OFNCTvHyLe+uXMqBZz3/Vcpm+WgTVzC5kaoUoT/d2I3P0EhstkU0Tl3vdrJUJIMgLMHbhx8bjYKzGRQ+5JzZEK59aHDwkP5ljQ+Vaj4mfePQ9TZysubfH4I7yD41zcAKR2q4WsuYaLNBEUaFym+cRW5+LDRsz1jQWsLpw7ElrYFQfv9mB6b9XxonmAeMH3+wvgzixjoxknhJBojxp6SAbVDT8eZNQUifsXLYWtiXtqa9sE8AP+fmw0X138Ufe4hK9el8utv5vhtAbZJ1KmVlTUH5hOJKgr3mY0V5Av/igR/5bnbxU6gbVPvDlrQzErsITV7PHORHS7OEQVocIZUXmPgrsrwb5t470HKofHWzqUkCrl8CSHZOKSthTKLw+3f8lWeXIUM8SIxvkhMJxHQTRwQOTcZkA0r1BLnqj4lOhw5kVu6R4Y6B7qp2/o=
  - secure: lcZkKigol6f+vXmZa8+OnfPTMSTP6Bp09LS74aw4fsoeEu/y5jJIM/aFd2xMRQ9IAL2Nh8CrPFqXrBzszVuQ9hUE4bg4Fw4Co/In4cIEYgnYwdGrdOy0qYLljemwtov0z/Dk4vAjsyVOEHw7Vs2zVystwOo1HQDkQTxd6tfvtA0Ee3K3lPM0v+L+oGc/uBachPocgj8LEJWBQzjbwHYO0+Yz/W3b+2UiTFqXH8/zV6E3xUzNJbfKh6gomB7Lp3Ay2SjYpNMkNXEoIc2MFm71aSZiWNi5mzJ8hCoEQ5bOU8Jsm0y9L5TBSpks9D4yAOCVU0FOGL3jmJMYPK7odrGjU2sVcuWcrMTJU90dNn764FpzKRrqlP78koESMI2cSeaDDbT+tSMiBrLJHlHHesrsHKeP6/U51Knl6BfkE+J7YdyYSxuHmtrski6aDcXCo12e7JST8YLnbup7MS1mNNBYb6/9jZAauH3MzxEqY/ePB+1K8eEaTaX0HvTxtGZRI8xRtLocax941AJCN1arO5AgS3zIc7Cc+EDyWZMbkKK14g8F0oCbcaRcsFcDNC0qtoKsmHVC7o3Q3gubxp3tdmTPRl93T6XKNPaqXjwMcUP+e2Swj8qOYdg9yMsSBw5J4TmyjFIkUqo034tm0dM5coDBpIwRjwCm0EpJNh2n2f5y5A8=
